#####################################################################################
#                                                                                   #
#    _____          _                            ____            _             _    #
#   |  ___|__  _ __| |_ _ __ ___  ___ ___       / ___|___  _ __ | |_ _ __ ___ | |   #
#   | |_ / _ \| '__| __| '__/ _ \/ __/ __|_____| |   / _ \| '_ \| __| '__/ _ \| |   #
#   |  _| (_) | |  | |_| | |  __/\__ \__ \_____| |__| (_) | | | | |_| | | (_) | |   #
#   |_|  \___/|_|   \__|_|  \___||___/___/      \____\___/|_| |_|\__|_|  \___/|_|   #
#                                                                                   #
#                                                                                   #
#           SOURCE CODE: https://github.com/DerFrZocker/Fortress-Control            #
#        BUG REPORTS: https://github.com/DerFrZocker/Fortress-Control/issues        #
#                    Donation: https://www.paypal.me/DerFrZocker                    #
#                 Patreon: https://www.patreon.com/woollydevelopment                #
#                                                                                   #
#####################################################################################


#####################################################################################
#                                                                                   #
#  NOTE: PLEASE KEEP IN MIND, THAT THE PLUGIN ONLY AFFECTS NEWLY GENERATED CHUNKS   #
#                                                                                   #
#####################################################################################

# see here https://minecraft.gamepedia.com/Custom#Generator_types (at the end of the Chapter) for a description,
# what 'spacing', 'separation' and 'salt' is.
# the default values in 1.16.2 are:
#  -> spacing    : 27
#  -> separation : 4
#  -> salt       : 30084232
#
# The 'separation' MUST be SMALLER than the 'spacing'
#
# If you want the "same" amount of fortress as in 1.15.2 use a 'spacing' of 17 - 18
# (17 generates slightly less fortress and 18 slightly more)
# and a 'separation' of 9

spacing: 27
separation: 4
salt: "default"
